[install]
# Configure package manager behavior
cache = true
exact = false
production = false

[test]
# Test configuration
coverage = true

[build]
# Build configuration
target = "bun"
outdir = "./dist"
splitting = false
minify = false
sourcemap = "external"