/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiServicesIndexRouteImport } from './routes/api/services.index'
import { Route as ApiServicesIdActionRouteImport } from './routes/api/services.$id.$action'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServicesIndexRoute = ApiServicesIndexRouteImport.update({
  id: '/api/services/',
  path: '/api/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServicesIdActionRoute = ApiServicesIdActionRouteImport.update({
  id: '/api/services/$id/$action',
  path: '/api/services/$id/$action',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/services/': typeof ApiServicesIndexRoute
  '/api/services/$id/$action': typeof ApiServicesIdActionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/services': typeof ApiServicesIndexRoute
  '/api/services/$id/$action': typeof ApiServicesIdActionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/services/': typeof ApiServicesIndexRoute
  '/api/services/$id/$action': typeof ApiServicesIdActionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/api/services/' | '/api/services/$id/$action'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/api/services' | '/api/services/$id/$action'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/services/'
    | '/api/services/$id/$action'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ApiServicesIndexRoute: typeof ApiServicesIndexRoute
  ApiServicesIdActionRoute: typeof ApiServicesIdActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/services/': {
      id: '/api/services/'
      path: '/api/services'
      fullPath: '/api/services/'
      preLoaderRoute: typeof ApiServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/services/$id/$action': {
      id: '/api/services/$id/$action'
      path: '/api/services/$id/$action'
      fullPath: '/api/services/$id/$action'
      preLoaderRoute: typeof ApiServicesIdActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ApiServicesIndexRoute: ApiServicesIndexRoute,
  ApiServicesIdActionRoute: ApiServicesIdActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
