import { ServiceType, HomelabConfig } from '../../core/types.js';
import { TemplateEngine } from '../../templates/engine.js';
import { BaseService } from '../base.js';
import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';

export class CloudflaredService extends BaseService {
  constructor(config: HomelabConfig, templateEngine: TemplateEngine) {
    super(
      'Cloudflare Tunnel',
      ServiceType.CLOUDFLARED,
      false,
      ['Caddy'],
      config,
      templateEngine
    );
  }

  protected async generateConfigFiles(): Promise<void> {
    try {
      const homeDir = process.env.HOME || process.env.USERPROFILE || '~';
      const configDir = join(homeDir, this.config.configPath, 'cloudflared');

      await mkdir(configDir, { recursive: true });

      const configContent = this.generateConfigYml();
      const configPath = join(configDir, 'config.yml');
      await writeFile(configPath, configContent);

      console.log(`Generated cloudflared config at ${configPath}`);
    } catch (error) {
      throw new Error(`Failed to generate cloudflared config: ${error}`);
    }
  }

  private generateConfigYml(): string {
    const tunnelDomain = this.config.tunnelDomain || this.config.domain;
    const routes = this.getServiceRoutes();

    let content = '# Cloudflared Tunnel Configuration\n';
    content += '# Generated by OnMind-HAL\n';
    content += '#\n';
    content += '# Cloudflare handles TLS at the edge.\n';
    content += '# Caddy on port 80 handles HTTP routing to containers.\n\n';

    content += 'tunnel: TUNNEL_ID\n';
    content += 'credentials-file: /etc/cloudflared/TUNNEL_ID.json\n\n';

    content += 'ingress:\n';

    for (const route of routes) {
      content += `  - hostname: ${route.hostname}\n`;
      content += `    service: http://caddy:80\n`;
    }

    content += '  # Catch-all rule (required)\n';
    content += '  - service: http_status:404\n';

    return content;
  }

  private getServiceRoutes(): Array<{ hostname: string }> {
    const tunnelDomain = this.config.tunnelDomain || this.config.domain;

    const serviceProxyMap: Record<string, string> = {
      [ServiceType.DOCKHAND]: 'dockhand',
      [ServiceType.ARCANE]: 'arcane',
      [ServiceType.COPYPARTY]: 'files',
      [ServiceType.DUCKDB]: 'duckdb',
      [ServiceType.RUSTFS]: 'rustfs',
      [ServiceType.RABBITMQ]: 'rabbitmq',
      [ServiceType.OLLAMA]: 'ollama',
      [ServiceType.OPENWEBUI]: 'openwebui',
      [ServiceType.OPENNOTEBOOKLM]: 'notebook',
      [ServiceType.N8N]: 'n8n',
      [ServiceType.KESTRA]: 'kestra',
      [ServiceType.KAFKAUI]: 'kafkaui',
      [ServiceType.KEYSTONEJS]: 'keystone',
      [ServiceType.KEYCLOAK]: 'keycloak',
      [ServiceType.AUTHELIA]: 'authelia',
      [ServiceType.POCKETID]: 'auth',
      [ServiceType.APISIX]: 'apisix',
      [ServiceType.FLOCI]: 'floci',
      [ServiceType.FLOCIAZ]: 'flociaz',
      [ServiceType.FLOCIGCP]: 'flocigcp',
      [ServiceType.K3D]: 'k3d',
      [ServiceType.FORGEJO]: 'forgejo',
      [ServiceType.ONEDEV]: 'onedev',
      [ServiceType.JENKINS]: 'jenkins',
      [ServiceType.SEMAPHORE]: 'semaphore',
      [ServiceType.BACKSTAGE]: 'backstage',
      [ServiceType.LIQUIBASE]: 'liquibase',
      [ServiceType.SONARQUBE]: 'sonarqube',
      [ServiceType.TRIVY]: 'trivy',
      [ServiceType.RAPIDOC]: 'rapidoc',
      [ServiceType.HOPPSCOTCH]: 'hoppscotch',
      [ServiceType.GRAFANA]: 'grafana',
      [ServiceType.LOKI]: 'loki',
      [ServiceType.PROMETHEUS]: 'prometheus',
      [ServiceType.OPENSEARCH]: 'opensearch',
      [ServiceType.QDRANT]: 'qdrant',
      [ServiceType.REDASH]: 'redash',
      [ServiceType.UPTIMEKUMA]: 'uptimekuma',
      [ServiceType.DOZZLE]: 'dozzle',
      [ServiceType.COROOT]: 'coroot',
      [ServiceType.REGISTRY]: 'registry',
      [ServiceType.NEXUS]: 'nexus',
      [ServiceType.INFISCAL]: 'secrets',
      [ServiceType.VAULT]: 'vault',
      [ServiceType.VAULTWARDEN]: 'vaultwarden',
      [ServiceType.LINKWARDEN]: 'linkwarden',
      [ServiceType.SHLINK]: 'shlink',
      [ServiceType.SEND]: 'send',
      [ServiceType.FILESTASH]: 'filestash',
      [ServiceType.SEAFILE]: 'drive',
      [ServiceType.EXCALIDRAW]: 'excalidraw',
      [ServiceType.DRAWIO]: 'drawio',
      [ServiceType.WISEMAPPING]: 'wisemapping',
      [ServiceType.KROKI]: 'kroki',
      [ServiceType.PRESENTON]: 'presenton',
      [ServiceType.SLIDEV]: 'slidev',
      [ServiceType.OUTLINE]: 'outline',
      [ServiceType.GRIST]: 'grist',
      [ServiceType.NOCODB]: 'nocodb',
      [ServiceType.DIRECTUS]: 'directus',
      [ServiceType.INSFORGE]: 'insforge',
      [ServiceType.SPARK]: 'spark',
      [ServiceType.TWENTYCRM]: 'crm',
      [ServiceType.CHATWOOT]: 'chatwoot',
      [ServiceType.MEDUSAJS]: 'shop',
      [ServiceType.HULY]: 'huly',
      [ServiceType.MATTERMOST]: 'mattermost',
      [ServiceType.CALCOM]: 'cal',
      [ServiceType.ADGUARD]: 'adguard',
      [ServiceType.JASPERREPORTS]: 'jasper',
      [ServiceType.DOCUSEAL]: 'docuseal',
      [ServiceType.STIRLINGPDF]: 'pdf',
      [ServiceType.PANDOCWEB]: 'pandoc',
      [ServiceType.CALIBREWEB]: 'books',
      [ServiceType.IMMICH]: 'photos',
      [ServiceType.LIBRETRANSLATE]: 'translate',
      [ServiceType.ORCAROUTERLITE]: 'orcarouter',
      [ServiceType.LITELLM]: 'litellm',
      [ServiceType.ANYTHINGLLM]: 'anythingllm',
      [ServiceType.VOICEBOX]: 'voicebox',
      [ServiceType.COPILOTKIT]: 'copilotkit',
      [ServiceType.GOOSE]: 'goose',
      [ServiceType.OPENCLAW]: 'openclaw',
      [ServiceType.FIRECRAWL]: 'firecrawl',
      [ServiceType.SEARXNG]: 'searxng',
      [ServiceType.PLAUSIBLE]: 'analytics',
      [ServiceType.NTFY]: 'ntfy',
      [ServiceType.MAILPIT]: 'mailpit',
      [ServiceType.LISTMONK]: 'listmonk',
      [ServiceType.HEADSCALE]: 'headscale',
      [ServiceType.WETTY]: 'wetty',
      [ServiceType.RUSTDESK]: 'rustdesk',
      [ServiceType.CODESERVER]: 'codeserver',
      [ServiceType.CONSUL]: 'consul',
      [ServiceType.HERMES]: 'hermes',
      [ServiceType.JUPYTERLAB]: 'jupyterlab',
      [ServiceType.PSITRANSFER]: 'psitransfer',
      [ServiceType.TOOLJET]: 'tooljet',
    };

    return this.config.selectedServices
      .filter(type => serviceProxyMap[type] !== undefined)
      .map(type => ({
        hostname: `${serviceProxyMap[type]}.${tunnelDomain}`,
      }));
  }

  getAccessUrl(): string {
    return 'https://dash.cloudflare.com (Cloudflare Dashboard)';
  }
}
